[package]
name = "oddity-sdp-protocol"
description = "SDP protocol implementation for oddity-rtsp-server."
version = "0.2.0"
authors = ["Oddity.ai Developers <hello@oddity.ai>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.21"
